# Generated by Django 5.1.6 on 2025-02-17 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetLink',
            fields=[
                ('resetTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachedEmail', models.TextField()),
                ('attachedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
