# Generated by Django 5.1.6 on 2025-02-18 07:54

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRootItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryEndPoint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('createdDate', models.DateTimeField(default=core.models.getCurrentTime)),
                ('SourceItemTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sourceType', models.TextField()),
                ('sourceLabel', models.TextField()),
                ('sourceContent', models.TextField()),
            ],
        ),
    ]
