# Generated by Django 5.1.6 on 2025-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apirootitem_sourceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirootitem',
            name='queryEndPoint',
            field=models.TextField(default=''),
        ),
    ]
