# Generated by Django 5.1.6 on 2025-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apirootitem_queryendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirootitem',
            name='inferenceApiKey',
            field=models.TextField(default=''),
        ),
    ]
