# Generated by Django 5.1.6 on 2025-02-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apirootitem_inferenceapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirootitem',
            name='scrapApiKey',
            field=models.TextField(default=''),
        ),
    ]
