# Generated by Django 5.1.6 on 2025-02-19 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_sourceitemtag_sourceitem_sourceitemtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('programTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programName', models.TextField()),
                ('programmeCode', models.TextField()),
                ('programmeStudyMode', models.TextField()),
                ('programmeDuration', models.TextField()),
                ('programLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TTProgram',
            fields=[
                ('ttProgramTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ttProgramName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableSlot',
            fields=[
                ('timeTableTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dayLabel', models.TextField()),
                ('lectureParticulars', models.TextField()),
                ('lectureDuration', models.TextField()),
                ('attachedProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tt_slots', to='core.ttprogram')),
            ],
        ),
    ]
