# Generated by Django 5.1.6 on 2025-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_programitem_ttprogram_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttprogram',
            name='ttProgramBatch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ttprogram',
            name='ttProgramYear',
            field=models.TextField(default=''),
        ),
    ]
