# Generated by Django 5.1.6 on 2025-02-20 12:46

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ttprogram_ttprogrambatch_ttprogram_ttprogramyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotItem',
            fields=[
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('timeTableTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('botLabel', models.TextField()),
                ('botSources', models.TextField()),
                ('botPrompt', models.TextField()),
                ('botSlug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='botLabel')),
            ],
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='usageCount',
            field=models.IntegerField(default=0),
        ),
    ]
