# Generated by Django 5.1.6 on 2025-02-20 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_botitem_sourceitem_usagecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMetricsItem',
            fields=[
                ('recordTag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programUsage', models.IntegerField()),
                ('ttUsage', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='botitem',
            old_name='timeTableTag',
            new_name='botTag',
        ),
    ]
