# Generated by Django 5.1.6 on 2025-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cachemetricsitem_rename_timetabletag_botitem_bottag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachemetricsitem',
            name='programUsage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cachemetricsitem',
            name='ttUsage',
            field=models.IntegerField(default=0),
        ),
    ]
