# Generated by Django 5.1.6 on 2025-02-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cachemetricsitem_programusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botitem',
            name='botAvatar',
            field=models.TextField(default=''),
        ),
    ]
